# This is a basic workflow to help you get started with Actions

name: deploy-to-production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    environment:
      name: production
      url: https://translate.tomyo.mn

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # node setup
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # python setup
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.7'
      # install private ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOY_KEY }} # zx_deployment
          known_hosts: 'dummy-hosts-key'

      - name: Adding Known Host
        run: ssh-keyscan -H translate.tomyo.mn > ~/.ssh/known_hosts

      - name: Install ansible
        run: |
          pip install ansible-core==2.14.10
          ansible-galaxy install ansistrano.deploy ansistrano.rollback
          ansible-galaxy collection install community.general

      - name: Deploy
        run: |
          CURRENT_DIR=$(pwd)
          git clone --branch master --single-branch git@github.com:T0mY0/tomyo-deployment.git "${CURRENT_DIR}/pipeline"
          ./scripts/build_artifact
          cp -f "${CURRENT_DIR}/deployment_artifact.tar.gz" "${CURRENT_DIR}/pipeline/translate/deployment_artifact.tar.gz"
          cd "${CURRENT_DIR}/pipeline/translate"
          ansible-playbook -i hosts deploy.yml
        env:
          CI: false
